import React, { useState } from 'react';
import { useSearchParams } from 'react-router-dom';
import { useQuery } from '@tanstack/react-query';
import { DownloadIcon } from 'lucide-react';
import { Button } from '../../components/ui/Button';
import { Card } from '../../components/ui/Card';
import { Input } from '../../components/ui/Field';
import { PageHeader } from '../../components/ui/PageHeader';
import { ScopeFilters, type Scope } from '../../components/ui/ScopeFilters';
import { EmptyState, QueryView } from '../../components/ui/States';
import { reportDefinitions, type ReportKey } from '../../data/reports';
import { api } from '../../services/api';
import { cn } from '../../utils/cn';
import { downloadCsv } from '../../utils/csv';
import { fmtDateTime } from '../../utils/format';

export function Reports() {
  const [params, setParams] = useSearchParams();
  const key = params.get('report') as ReportKey ?? 'workforce-summary';
  const [scope, setScope] = useState<Scope>({ category: '', platform: params.get('platform') ?? '', dept: '', shift: '' });
  const [from, setFrom] = useState('');
  const [to, setTo] = useState('');
  const def = reportDefinitions.find((r) => r.key === key) ?? reportDefinitions[0];
  const q = useQuery({ queryKey: ['report', key, scope, from, to], queryFn: () => api.getReport(key, { ...scope, from, to }) });
  const groups = [...new Set(reportDefinitions.map((r) => r.group))];

  return (
    <div>
      <PageHeader title="Reports" description="Operational reports generated by the reporting API. Export to CSV where supported." />
      <div className="grid gap-4 lg:grid-cols-[260px_1fr]">
        <Card className="h-fit p-2">
          {groups.map((g) =>
          <div key={g} className="mb-2">
              <p className="px-3 py-1.5 text-[11px] font-semibold uppercase tracking-wide text-ink-subtle">{g}</p>
              {reportDefinitions.filter((r) => r.group === g).map((r) =>
            <button key={r.key} onClick={() => setParams({ report: r.key })} className={cn('block w-full rounded-lg px-3 py-1.5 text-left text-[13px]', r.key === key ? 'bg-primary-50 font-semibold text-primary-700' : 'hover:bg-mist')}>{r.title}</button>
            )}
            </div>
          )}
        </Card>
        <Card>
          <div className="border-b border-line p-4">
            <div className="flex flex-wrap items-start justify-between gap-2">
              <div><h2 className="text-base font-semibold">{def.title}</h2><p className="text-xs text-ink-muted">{def.description}</p></div>
              <Button size="sm" variant="secondary" disabled={!q.data?.rows.length} icon={<DownloadIcon className="h-3.5 w-3.5" />} onClick={() => q.data && downloadCsv(q.data.columns, q.data.rows, `${key}.csv`)}>Export CSV</Button>
            </div>
            <div className="mt-3 flex flex-wrap gap-2">
              <ScopeFilters value={scope} onChange={setScope} />
              <Input type="date" aria-label="From" value={from} onChange={(e) => setFrom(e.target.value)} className="h-9 w-40" />
              <Input type="date" aria-label="To" value={to} onChange={(e) => setTo(e.target.value)} className="h-9 w-40" />
            </div>
          </div>
          <QueryView query={q} isEmpty={(d) => d.rows.length === 0} empty={<EmptyState title="No data for these filters" />}>
            {(d) =>
            <>
                <div className="scroll-thin max-h-[600px] overflow-auto">
                  <table className="w-full text-[13px]">
                    <thead className="sticky top-0 bg-mist">
                      <tr>{d.columns.map((c) => <th key={c} scope="col" className="px-4 py-2.5 text-left text-[11px] font-semibold uppercase tracking-wide text-ink-subtle">{c}</th>)}</tr>
                    </thead>
                    <tbody>
                      {d.rows.map((r, i) =>
                    <tr key={i} className="border-b border-line last:border-0">{r.map((v, j) => <td key={j} className={cn('px-4 py-2', typeof v === 'number' && 'tabular')}>{v}</td>)}</tr>
                    )}
                    </tbody>
                  </table>
                </div>
                <p className="border-t border-line px-4 py-2 text-[11px] text-ink-subtle">{d.rows.length} rows · generated {fmtDateTime(d.generatedAt)}</p>
              </>
            }
          </QueryView>
        </Card>
      </div>
    </div>);

}